'use client';

import { company } from '@/data/company';
import { Mail, Phone, MessageCircle, MapPin } from 'lucide-react';
import { Breadcrumb } from '@/components/ui/Breadcrumb';
import { SecondaryButton } from '@/components/ui/SecondaryButton';
import { cn } from '@/lib/utils';

/* ────────────────────────────────────────────
   Office coordinates — verified landmark location for I-thum Tower A,
   Plot A-40, Sector 62, Noida. Used by the OpenStreetMap embed (which
   requires numeric lat/lon) and kept here as a single source of truth.
   ──────────────────────────────────────────── */
export const officeCoordinates = { lat: 28.6258, lon: 77.3658 };

/* Exact encoded Google Maps destination URL — used for Get Directions and
   the footer address link (both open in a new tab, no iframe involved).
   Google's `maps.google.com/maps?...&output=embed` endpoint returns 404 +
   `x-frame-options: SAMEORIGIN`, so we do NOT use it as an iframe src. */
const OFFICE_FULL_ADDRESS = `${company.name}, ${company.address.line1}, ${company.address.line2}, ${company.address.city}, ${company.address.state} ${company.address.pincode}, ${company.address.country}`;

export const officeMapsDirectionsUrl = `https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent(
  OFFICE_FULL_ADDRESS
)}`;

/* OpenStreetMap embed URL — privacy-conscious, no API key, returns 200 with
   no x-frame-options restrictions. Used for the interactive iframe after the
   user clicks the static preview. Bounding box centred on the office
   coordinates with a ~0.02° span (≈2 km) at zoom ~15. */
const OSM_BBOX_DELTA = 0.01;
export const officeOsmEmbedUrl =
  `https://www.openstreetmap.org/export/embed.html` +
  `?bbox=${officeCoordinates.lon - OSM_BBOX_DELTA}%2C${officeCoordinates.lat - OSM_BBOX_DELTA}` +
  `%2C${officeCoordinates.lon + OSM_BBOX_DELTA}%2C${officeCoordinates.lat + OSM_BBOX_DELTA}` +
  `&layer=mapnik&marker=${officeCoordinates.lat}%2C${officeCoordinates.lon}`;

/* Static SVG map preview shipped locally (no third-party request before
   user interaction). Generated by scripts/generate-contact-map-preview.py. */
export const officeMapPreviewSrc = '/media/contact/office-map-preview.svg';

/* ────────────────────────────────────────────
   Compact contact rows (replaces the old card grid)
   Each row: small icon + short metadata label + actionable value.
   Phone row groups Primary + Secondary into one row.
   ──────────────────────────────────────────── */

interface ContactRow {
  icon: React.ReactNode;
  label: string;
  value: React.ReactNode;
  href?: string;
  external?: boolean;
  /* When `phoneGroup` is true, `value` is treated as a compound block
     with two phone items. */
  phoneGroup?: boolean;
}

const contactRows: ContactRow[] = [
  {
    icon: <Mail className="size-4 text-be-yellow-600" />,
    label: 'Email',
    value: company.email,
    href: `mailto:${company.email}`,
  },
  {
    icon: <Phone className="size-4 text-be-yellow-600" />,
    label: 'Phone',
    phoneGroup: true,
    value: (
      <div className="flex flex-col gap-0.5">
        <a
          href={`tel:${company.phonePrimaryTel}`}
          className="font-medium text-be-charcoal-950 hover:text-be-yellow-600 transition-colors"
        >
          <span className="text-metadata text-be-grey-650 mr-1.5">Primary:</span>
          {company.phonePrimary}
        </a>
        <a
          href={`tel:${company.phoneSecondaryTel}`}
          className="font-medium text-be-charcoal-950 hover:text-be-yellow-600 transition-colors"
        >
          <span className="text-metadata text-be-grey-650 mr-1.5">Secondary:</span>
          {company.phoneSecondary}
        </a>
      </div>
    ),
  },
  {
    icon: <MessageCircle className="size-4 text-be-yellow-600" />,
    label: 'WhatsApp',
    value: 'Chat on WhatsApp',
    href: company.whatsapp.href,
    external: true,
  },
  {
    icon: <MapPin className="size-4 text-be-yellow-600" />,
    label: 'Address',
    value: (
      <>
        {company.address.line1}, {company.address.line2},
        <br />
        {company.address.city}, {company.address.state} — {company.address.pincode}
      </>
    ),
    href: officeMapsDirectionsUrl,
    external: true,
  },
];

/* ────────────────────────────────────────────
   Top of left column — Chapter 1
   Breadcrumb, contact-specific H1 (max two lines on
   large desktop), supporting paragraph, compact
   contact rows, response-time statement.
   ──────────────────────────────────────────── */

export default function ContactIntro() {
  return (
    <div className="reveal-up flex flex-col gap-5">
      {/* Breadcrumb */}
      <Breadcrumb items={[{ label: 'Home', href: '/' }, { label: 'Contact Us' }]} />

      {/* Title + supporting paragraph */}
      <div className="flex flex-col gap-2.5">
        <h1 className="text-contact-h1 text-be-charcoal-950">
          Contact Bharat Electrosafe
        </h1>
        <p className="text-body-large text-be-grey-650">
          Reach our team for product enquiries, technical support, quotations or application guidance.
        </p>
      </div>

      {/* Compact contact rows — vertical padding trimmed ~15-20% */}
      <ul className="flex flex-col">
        {contactRows.map((row, idx) => (
          <li
            key={row.label}
            className={cn(
              'flex items-start gap-3 py-2.5 min-h-[44px]',
              idx !== contactRows.length - 1 && 'border-b border-be-grey-150'
            )}
          >
            <span
              aria-hidden
              className="flex h-8 w-8 shrink-0 items-center justify-center rounded-md bg-be-yellow-50 border border-be-yellow-100 mt-0.5"
            >
              {row.icon}
            </span>
            <div className="flex flex-col gap-0.5 min-w-0">
              <span className="text-metadata font-semibold text-be-grey-650 uppercase tracking-wide">
                {row.label}
              </span>
              {row.href && !row.phoneGroup ? (
                <a
                  href={row.href}
                  target={row.external ? '_blank' : undefined}
                  rel={row.external ? 'noopener noreferrer' : undefined}
                  className="text-body font-medium text-be-charcoal-950 hover:text-be-yellow-600 transition-colors break-words"
                >
                  {row.value}
                </a>
              ) : row.phoneGroup ? (
                <div className="text-body">
                  {row.value}
                </div>
              ) : (
                <span className="text-body font-medium text-be-charcoal-800 break-words">
                  {row.value}
                </span>
              )}
            </div>
          </li>
        ))}
      </ul>

      {/* Response-time statement */}
      <p className="text-metadata text-be-grey-650">
        We normally respond within one business day.
      </p>
    </div>
  );
}

/* ────────────────────────────────────────────
   Full-width immediate-assistance strip
   Rendered below both desktop columns so the form
   and contact column end at the same visual point.
   ──────────────────────────────────────────── */

export function ImmediateAssistanceStrip() {
  return (
    <div className="reveal-up rounded-lg border border-be-grey-250 bg-be-yellow-50 px-5 py-4 md:py-5 mt-7 md:mt-8 flex flex-col md:flex-row md:items-center md:justify-between gap-3 md:gap-6">
      {/* Left — text */}
      <div className="flex flex-col gap-1 min-w-0">
        <p className="text-body font-semibold text-be-charcoal-950">
          Need immediate assistance?
        </p>
        <p className="text-body text-be-grey-650">
          Call our sales team directly for product selection guidance and quotation support.
        </p>
      </div>

      {/* Right — actions */}
      <div className="flex flex-col sm:flex-row gap-2.5 md:shrink-0">
        <SecondaryButton
          href={`tel:${company.phonePrimaryTel}`}
          className="w-full sm:w-auto"
        >
          <Phone className="size-4 mr-1.5" />
          Call Sales
        </SecondaryButton>
        <SecondaryButton
          href={company.whatsapp.href}
          target="_blank"
          className="w-full sm:w-auto"
        >
          <MessageCircle className="size-4 mr-1.5" />
          WhatsApp
        </SecondaryButton>
      </div>
    </div>
  );
}
